# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
     docker:
      - image: circleci/python:3.7
    
     working_directory: ~/devops/devops

     steps:
      #Step 1: Obtain repo from GitHub
      -  checkout
      #Step 2: Create a virtual environment and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      #Step 3: Run codeing convention software and also the tester
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=env* --statistics
            # pytest -v --cov=calculator
            pytest --junitxml=test-results/junit.xml
      #Step 4: Deploy software to DEPLOY-(CURRENT_DATE)
      - run:
          name: deploy_software
          command: |
            cd
            mkdir DEPLOY-$(date +"%d-%m-%Y")
            cd DEPLOY-$(date +"%d-%m-%Y")
            cp ~/devops/devops/calculator/calculator.py ~/DEPLOY-$(date +"%d-%m-%Y")
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

       
      